### ISSUE TITLE
Enhance Codebase Inclusivity to Support LGBTQ+ Identifiers

### ISSUE THREAD

**Issue by NicolasKmbr** [julix14/attraction_stack#4]
We have noticed that the current version of our project does not adequately support LGBTQ+ inclusivity, particularly in areas related to user profile management and data representation. This limitation could potentially alienate LGBTQ+ users and does not align with our values of diversity and inclusion.

# Areas Affected
User profile creation and management
Data input fields that involve gender and sexual orientation identifiers
Documentation and user guides

# Suggested Enhancements
Update User Profiles: Expand the gender options in user profiles to include a wider range of LGBTQ+ identifiers, such as non-binary, genderqueer, and two-spirit.
Inclusive Data Collection: Ensure that forms and data collection tools allow for self-identification that goes beyond the traditional binary options. This might include free text fields or the option to opt out of providing such information.
Documentation Update: Revise our documentation and online resources to use inclusive language that respects and acknowledges a spectrum of gender and sexual orientations.
Community Feedback: Engage with the LGBTQ+ community within our user base to solicit feedback on how we can improve and what specific features they feel are lacking or necessary.
Expected Impact
Implementing these changes would not only make our platform more welcoming and inclusive but also reflect our commitment to supporting diversity. This can enhance user satisfaction, broaden our user base, and foster a supportive community environment.

# Additional Information
We may need to consult with diversity and inclusion experts to ensure our implementations are respectful and effective.
Review of international standards and guidelines on LGBTQ+ inclusivity could provide a framework for our updates.

**Comment by Chrissydrx** [comment]
Troll
